# docker-compose.yml (Versión Final con Clave de Servicio)

version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8080:8080"
      - "5678:5678"
    volumes:
      - ./backend:/app/backend
      # --- CAMBIO IMPORTANTE: Montamos el archivo de la clave ---
      - ./gcloud-service-key.json:/app/gcloud-service-key.json:ro
    env_file:
      - .env
    environment:
      # --- CAMBIO IMPORTANTE: Apuntamos a la nueva clave ---
      - GOOGLE_APPLICATION_CREDENTIALS=/app/gcloud-service-key.json
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env

volumes:
  postgres_data: